### PR TITLE
Feature/demo tidy up

### PR DESCRIPTION
**Pull request by davestewart**
Major demo tidy up; should make it easier for Vue folks to get started, and the demo to be extended in future:

- rebuilt all files using Standard JS, as per ESLint settings
- converted programatic styles to inline styles
- did a bunch of CSS housekeeping
- removed old Vue demo files
- made demo folder structure more sensible
- moved demo folder to root
- updated build scripts

This PR relies on #38, so probably best to merge that first.

### CODE REVIEW

**Comment by davestewart** [comment]
Was thinking about this a bit more last night, and I know you have 4 dependent libraries, but for me, I think the ideal folder structure for all Smooth DnD libraries would be:

```
+- demo
|   +- build
|   +- config
|   +- src
|   |   +- ...
|   +- ...
+- src
|   +- components
|   +- ...
+- ...
```

The core lib should always in `src`, and the demo always in `demo`.

This also allows you top-level `docs` and `test` folders; see some of my libs for comparison:

- https://github.com/davestewart/vuex-pathify
- https://github.com/davestewart/javascript-state-machine
- https://github.com/davestewart/axios-actions

**Comment by kutlugsahin** [comment]
Hey Dave,
This is indeed a nice catch. It make sense to have the library related code in the src folder. Let me add this in the todo list

**Comment by davestewart** [comment]
Coolio :)

You want me to go ahead with a PR?

**Comment by davestewart** [comment]
Hey,

Refactoring now. 

I noticed some related issues around `package.json` and published files from the source `smooth-dnd` which is publishing all files to NPM including src.

I'll drop some notes in the PR when I submit, around making the libs consistent and easier to manage!

**Pull request merged**
