### PR TITLE
Feature/folder refactor

### PR DESCRIPTION
**Pull request by davestewart**
Hey @kutlugsahin,

This is just about ready to go, but I wanted to check a few things first.

### Repo

- https://github.com/davestewart/vue-smooth-dnd/tree/feature/folder-refactor

### Changes

Refactor:

- create / move folders

Build:

- add Rollup as bundle builder
- add banner to bundled plugin
- update package.json for NPM

Linting:

- add ESLint
- add `lint` script
- enforce Standard style

Demo / docs:

- prepare for Netlify
- added CodeSandbox links
- update READMEs

### Summary

The main changes are:

- the package now uses Rollup to bundle. I've been using this a while and it's great! Super small packages and next to no configuration.

- the demo is now self-contained

- `package.json` now only includes `dist` files

- overall the files, dependencies and docs are a lot cleaner! 

Also, I see you removed package-lock.json. This file is generally [recommended to be included](https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494) in the repo.

Though, reading through that post again, it seems that some people think that you don't need it when publishing a package. I'd say, this **is** the case, but only in the *published* files; `dist`. The thing is, NPM doesn't publish this by default (see output in a message below); so I think it should still be committed to the original repo. 

Anyway, it looked like the disparity from both repos is what's stopping the PR from being automatically merged.

Thassit for now, until I make any updates...

### CODE REVIEW

**Comment by davestewart** [comment]
Next question: what is the version of VSDND?

The repo root says `1.0.0` but the subfolder says `0.2.5`.

Also, no tagged releases. Might want to start this! (I can advise).

**Comment by davestewart** [comment]
Just tested a publish, and this is what we get, so all good:

```
Dave $ npm publish --dry-run
npm notice
npm notice 📦  vue-smooth-dnd@1.0.0
npm notice === Tarball Contents ===
npm notice 1.8kB  package.json
npm notice 11.6kB README.md
npm notice 5.4kB  dist/vue-smooth-dnd.esm.js
npm notice 6.3kB  dist/vue-smooth-dnd.js
npm notice 3.4kB  dist/vue-smooth-dnd.min.js
npm notice === Tarball Details ===
npm notice name:          vue-smooth-dnd
npm notice version:       1.0.0
npm notice package size:  7.3 kB
npm notice unpacked size: 28.5 kB
npm notice shasum:        020d214939de38919a2e23b27e3435ec1dd6622f
npm notice integrity:     sha512-26FvwmjfnYZm2[...]/laLOdpz7NxpQ==
npm notice total files:   5
npm notice
+ vue-smooth-dnd@1.0.0
```

**Comment by davestewart** [comment]
Hey @kutlugsahin - any time to give this some attention!?

**Comment by DannyFeliz** [comment]
Merge this please!

**Comment by kutlugsahin** [comment]
Hey @davestewart, I am finally on it. I merged to a branch to make some updates then I will merge to master. I want to keep semicolons for instance :) and add some npm scripts. By the way why switched to rollup instead of webpack do we need that switch ? Thanks

**Comment by kutlugsahin** [comment]
I guess in this setup we will publish the whole workspace to the npm even with demo folder. I prefer to have a separate folder containing only the source and build files of library to publish. Can we do something for it? And also your rollup is installed globally I guess, I added it as a local dev dependency. Cheers!

**Comment by davestewart** [comment]
Hey @kutlugsahin!

I'm just going for a walk then will answer your Qs.

Well done!

**Comment by davestewart** [comment]
> I prefer to have a separate folder containing only the source and build files of library to publish

Yeah, with the rollup build, they'll build to `dist`. The package `files` entry makes sure only those files go up to npm.

**Comment by davestewart** [comment]
As for Rollup, it's just optimised for libraries, unlike webpack which is optimised for apps. Everything is less; config, build, output.

Try it and see!

**Comment by davestewart** [comment]
> I want to keep semicolons for instance

Ha! I don't miss semicolons at all, but it's your library 😋

I applied the Standard style which you can undo of course, but so many people use it these days.

Again, I stopped worrying and accepted it.

**Comment by kutlugsahin** [comment]
OK let's give rollup a try 👍. I may be bit old fashioned but will keep the semicolons though 😄.
There is one thing left then which is that the package dependencies have some libraries used for demo app. like vue-router, object-assign etc. those libs will also be installed with the lib itself right even the project does not need them. We should find a solution for them

**Comment by davestewart** [comment]
> the package dependencies have some libraries used for demo app. like vue-router, object-assign etc

The demo is its own package, so just move the deps there!

**Comment by kutlugsahin** [comment]
Yes I saw that and removed, it works fine. I think the publish script to github pages is gone. I need to add it. I also added two new properties yesterday I'll update readme for that. Then we are good to go.

**Comment by kutlugsahin** [comment]
No those are left from merge :) never mind.

**Comment by davestewart** [comment]
> but I need to take them off the npm package

Only the files mentioned in the package.json files node will be published to npm.

See the publish log I pasted above:

https://github.com/kutlugsahin/vue-smooth-dnd/pull/40#issuecomment-423610226

**Comment by kutlugsahin** [comment]
added the gh-pages script. all good to go. I'll merge it to master now

**Comment by davestewart** [comment]
Now to port the readme to the other libs 😋

**Comment by kutlugsahin** [comment]
Oh readme! Forgot it totally. I have to update it before merge

**Pull request merged**
